// Code generated by MockGen. DO NOT EDIT.
// Source: audit-log/internal/auditlog/usecases (interfaces: EventStore)
//
// Generated by this command:
//
//	mockgen -destination=test/unit/doubles/auditlog/eventstore_mock.go -package=auditlogdoubles audit-log/internal/auditlog/usecases EventStore
//

// Package auditlogdoubles is a generated GoMock package.
package auditlogdoubles

import (
	domain "audit-log/internal/auditlog/domain"
	usecases "audit-log/internal/auditlog/usecases"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEventStore is a mock of EventStore interface.
type MockEventStore struct {
	ctrl     *gomock.Controller
	recorder *MockEventStoreMockRecorder
	isgomock struct{}
}

// MockEventStoreMockRecorder is the mock recorder for MockEventStore.
type MockEventStoreMockRecorder struct {
	mock *MockEventStore
}

// NewMockEventStore creates a new mock instance.
func NewMockEventStore(ctrl *gomock.Controller) *MockEventStore {
	mock := &MockEventStore{ctrl: ctrl}
	mock.recorder = &MockEventStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStore) EXPECT() *MockEventStoreMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockEventStore) FindByID(ctx context.Context, id uuid.UUID) (*domain.AuditEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.AuditEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockEventStoreMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockEventStore)(nil).FindByID), ctx, id)
}

// Query mocks base method.
func (m *MockEventStore) Query(ctx context.Context, opts usecases.QueryEventsOptions) ([]*domain.AuditEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, opts)
	ret0, _ := ret[0].([]*domain.AuditEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockEventStoreMockRecorder) Query(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockEventStore)(nil).Query), ctx, opts)
}

// Save mocks base method.
func (m *MockEventStore) Save(ctx context.Context, event *domain.AuditEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockEventStoreMockRecorder) Save(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockEventStore)(nil).Save), ctx, event)
}
