// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"audit-log/internal/auditlog/grpcapi"
	"audit-log/internal/auditlog/persistence"
	"audit-log/internal/auditlog/usecases"
	"audit-log/internal/infra/grpcserver"
	"audit-log/proto/auditlogv1"
	"google.golang.org/grpc"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeGRPC(db *gorm.DB) (*grpc.Server, error) {
	eventRepository := persistence.NewEventRepository(db)
	simpleAuditService := usecases.NewSimpleAuditService(eventRepository)
	server := grpcapi.NewServer(simpleAuditService)
	grpcServer := registerAuditLogGRPC(server)
	return grpcServer, nil
}

func InitializeService(db *gorm.DB) (usecases.AuditService, error) {
	eventRepository := persistence.NewEventRepository(db)
	simpleAuditService := usecases.NewSimpleAuditService(eventRepository)
	return simpleAuditService, nil
}

// wire.go:

func registerAuditLogGRPC(api *grpcapi.Server) *grpc.Server {
	srv := grpcserver.New()
	auditlogv1.RegisterAuditLogServer(srv, api)
	return srv
}
